version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: oauth2db
    ports:
      - "5432:5432"
    networks:
      - oauth2_network

networks:
  oauth2_network:
    driver: bridge
