version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: oauth2db
    ports:
      - "5432:5432"
    networks:
      - oauth2_network

  dev:
    image: mcr.microsoft.com/devcontainers/java:17-bullseye
    volumes:
      - ..:/workspace:cached
    networks:
      - oauth2_network
    depends_on:
      - db
    command: sleep infinity

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ../angular-15-client:/app
    command: sh -c "npm install && npm run start -- --host 0.0.0.0"
    ports:
      - "4200:4200"
    networks:
      - oauth2_network
    environment:
      - CHOKIDAR_USEPOLLING=true


volumes:
  db-data:

networks:
  oauth2_network:
    driver: bridge
